version: '3.8'

services:
  order-service:
    container_name: order-service
    build:
      context: ../OrderService
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-order:5432/order-service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      USER_SERVICE_BASE_URL: http://user-service:8080/api/v1/users
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8082:8082"
    depends_on:
      - postgres-order
      - user-service
      - kafka
    networks:
      - innowise-network

  api-gateway:
    container_name: api-gateway
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET:-mySecretKeymySecretKeymySecretKeymySecretKey}
    ports:
      - "8083:8083"
    depends_on:
      - auth-service
      - user-service
      - order-service
      - payment-service
    networks:
      - innowise-network

  payment-service:
    build: ../PaymentService
    container_name: payment-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
      - kafka
    networks:
      - innowise-network
    restart: unless-stopped

  user-service:
    container_name: user-service
    build:
      context: ../UserService
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/user-service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATA_REDIS_HOST: redis
    ports:
      - "8080:8080"
    depends_on:
      - postgres-user
      - redis
    networks:
      - innowise-network

  auth-service:
    container_name: auth-service
    build:
      context: ../AuthService
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth-service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: ${JWT_SECRET:-mySecretKeymySecretKeymySecretKeymySecretKey}
    ports:
      - "8081:8081"
    depends_on:
      - postgres-auth
    networks:
      - innowise-network

  postgres-auth:
    container_name: auth-postgres
    image: postgres:16
    environment:
      POSTGRES_DB: auth-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_auth_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - innowise-network

  postgres-user:
    image: postgres:16
    container_name: user-postgres
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pg_user_data:/var/lib/postgresql/data
    networks:
      - innowise-network

  postgres-order:
    image: postgres:16
    container_name: order-postgres
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - pg_order_data:/var/lib/postgresql/data
    networks:
      - innowise-network

  mongodb:
    image: mongo:5.0
    container_name: mongo-payment
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=payments
    volumes:
      - mongodb_data:/data/db
    networks:
      - innowise-network
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: payment-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - innowise-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - innowise-network
    restart: unless-stopped

  redis:
    image: redis:7
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    networks:
      - innowise-network

volumes:
  mongodb_data:
  pg_user_data:
  pg_order_data:
  pg_auth_data:

networks:
  innowise-network:
    driver: bridge